TestR : Main.o Account.o Stockage.o
	gcc -o TestR Main.o Account.o Stockage.o

Main.o : ./Main.c
	gcc -o Main.o -c ./Main.c

Account.o : ./Account.c
	gcc -o Account.o -c ./Account.c

Stockage.o : ./Stockage.c
	gcc -o Stockage.o -c ./Stockage.c